### ISSUE TITLE
PacketStream not working with "" and without "" Using proxies

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#6] opened 2023-05-22 19:06 UTC
PacketStream not working with "" and without "" Using proxies

{"ok":false,"message":"Error: Unable to connect to validation server."}
{"ok":false,"message":"Error: Unable to connect to validation server."}
{"ok":false,"message":"Error: Unable to connect to validation server."}
{"ok":false,"message":"Error: Unable to connect to validation server."}

**Comment by engageub** [comment] 2023-05-22 19:24
Could you please let me know if it is working on your PC with the direct command mentioned in packetstream website.
https://hub.docker.com/r/packetstream/psclient

Thank you

**Comment by SkullFace141** [comment] 2023-05-22 19:29
I think its proxy issue

**Comment by engageub** [comment] 2023-05-22 19:40
can you update the code now. Some environment variables related to proxies have been removed to maintain consistency with other applications. Can you download and let me know. I don't have proxies to test now which packetstream accepts. 
Thank you

**Comment by SkullFace141** [comment] 2023-05-22 19:42
ok

**Comment by SkullFace141** [comment] 2023-05-22 19:45
btw last time when i restarted the system all containers went crazy and i had to delete them and start from scratch

**Comment by SkullFace141** [comment] 2023-05-22 19:47
I am using socks5 prxoies with this format socks5://user:pass@host:ip

**Comment by SkullFace141** [comment] 2023-05-22 19:49
its working now after changes, please revise changes before commits

**Comment by engageub** [comment] 2023-05-22 19:52
Yes that should be fine now since environment variables have been removed now. 
The format in proxies.txt is correct. 
Please look into your container logs now by enabling logs in properties.conf. Make sure your proxies are considered residential otherwise it will not work. Sometimes even residential proxies are considered non residential by packetstream. So you need to validate the IP's from the subnet you are using. 
The residential proxies which were working for me till last month were not considered residential this month. 
So you need to look into the logs before using the proxies. Also remove the proxies if there are not considered residential else your account may be blocked. 

Thank you

**Comment by engageub** [comment] 2023-05-22 19:53
If their containers do internal updates, it will not be known easily unless there is some issue. 

Thank you

**Comment by engageub** [comment] 2023-05-22 19:56
If the system is rebooted, the containers have to be started in sequence. I think there will be one more update required when you reboot the system. I am aware of one issue where the proxy containers don't allow dns after the reboot.
You may expect update on that. 

Thank you

**Comment by engageub** [comment] 2023-05-22 20:03
I see that it was working normally even before without proxies. I don't know why it was not working for you. May be their server had network issue at that time or you did not set the config properly. I tried the old code now with direct connection and is working fine.
Thank you

**Comment by SkullFace141** [comment] 2023-05-22 20:04
it was script issue so far proxies connect now

**Comment by SkullFace141** [comment] 2023-05-22 20:17
please update the script with container start order

**Comment by engageub** [comment] 2023-05-22 20:24
I use environment variables to connect to packetstream usually.
So I think it was using both environment variable and also network. It was doing proxy over proxy connection which might not have been successful in your case. 

Thank you

**Comment by engageub** [comment] 2023-05-22 20:29
> please update the script with container start order

I did not understand what you mean. Could you please elaborate.

Thank you

**Comment by SkullFace141** [comment] 2023-05-22 20:34
make a container restarted in correct order

**Comment by SkullFace141** [comment] 2023-05-22 20:48
its just the idea that you have to setup everything from scratch every reboot

**Comment by engageub** [comment] 2023-05-22 20:51
No, they will automatically be started on their own. It was configured that way.
But there might be dns issue if your proxy does not support UDP protocol. Otherwise that should be fine. 
Have you rebooted and faced any issue? Did you see any errors in logs?

Thank you

**Comment by SkullFace141** [comment] 2023-05-22 20:55
no errors on test run

**Comment by engageub** [comment] 2023-05-22 21:07
In that case it is not required for any further updates.

**Comment by engageub** [comment] 2023-05-22 21:45
I tried the old code with my proxy server and is working fine. From the logs I see the following. So it was intermittently failing. 
The issue is not with the script. May be the way your proxy server is configured can also be an issue. Or your password has some special characters which might have been misinterpreted by the packetstream client or packetstream server has issue when you used the script.


{"ok":true,"message":"PacketStream background process is running."}
{"ok":true,"message":"PacketStream background process is running."}
{"ok":true,"message":"PacketStream background process is running."}
{"ok":true,"message":"PacketStream background process is running."}
{"ok":false,"message":"Error: Unable to connect to validation server."}
{"ok":false,"message":"Error: Unable to connect to validation server."}
{"ok":true,"message":"PacketStream background process is running."}
{"ok":true,"message":"PacketStream background process is running."}



Thank you

**Comment by engageub** [comment] 2023-05-22 21:46
I am closing the issue since no further updates are required and script is working as expected.

**Closed by engageub** 2023-05-22 21:46 UTC
