### ISSUE TITLE
On a service provider VPS this doesn't work

### ISSUE THREAD

**Issue by neve360** [engageub/InternetIncome#169] opened 2024-11-13 16:33 UTC
Hi, I tried this project on my local machine with ubuntu server 24 and on there worked perfectly but after I transferred the same files to the google vps it starts but seems like the machine can't connect thru the proxy, if I try to run curl to a page with the proxy that works. I checked docker logs and the tun2socks seems working 2 info logs 0 warn or other messages if I run the ifconfig -a I can see the 2 interface.

**Comment by neve360** [comment] 2024-11-13 16:57
now I tried with tun proxy branch and this it gives this error in the tun proxys containers [2024-11-13T16:54:28Z WARN  tproxy_config::linux] failed to bind mount custom resolv.conf onto /etc/resolv.conf, resorting to direct write
[2024-11-13T16:54:28Z ERROR tun2proxy] main loop error: Read-only file system (os error 30)

**Comment by neve360** [comment] 2024-11-13 19:19
this is what I get in the tun of main branch time="2024-11-13T19:16:59Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2024-11-13T19:16:59Z" level=info msg="[STACK] tun://tun0 <-> http://ip:port"

**Comment by engageub** [comment] 2024-11-13 22:12
> now I tried with tun proxy branch and this it gives this error in the tun proxys containers [2024-11-13T16:54:28Z WARN tproxy_config::linux] failed to bind mount custom resolv.conf onto /etc/resolv.conf, resorting to direct write [2024-11-13T16:54:28Z ERROR tun2proxy] main loop error: Read-only file system (os error 30)

Tun2Proxy has restricted permissions in the recent versions. 
There is an open issue related to this https://github.com/tun2proxy/tun2proxy/issues/131

However, the code has been updated to use the latest version of tun2proxy now. 
You can try tun2proxy if tun2socks does not work.
Please download the code again for tun2proxy if you wish to access the latest version. 

Thank you

**Comment by neve360** [comment] 2024-11-14 06:21
im using http proxy(on my home server that works with tunsocks) btw here uname -r            
6.8.0-1015-gcp

**Comment by engageub** [comment] 2024-11-14 07:09
> im using http proxy(on my home server that works with tunsocks) btw here uname -r 6.8.0-1015-gcp

Is this the kernel version on your VPS or your home PC?

Have you tried the latest tun2proxy branch?

Thank you

**Comment by engageub** [comment] 2024-11-14 07:54
I had a look at tun2socks issues and it looks like other users have problems running tun2socks on google VPS.

https://github.com/xjasonlyu/tun2socks/issues/363

You can use tun2proxy instead, if you have problems on that VPS.

I also see that you made a comment recently, but the issue is in closed state.
You may want to open the issue if the issue persists with tun2socks. 


Thank you

**Comment by neve360** [comment] 2024-11-14 14:24
now i try with tunproxy, btw yes that was the output of the google vps

**Comment by neve360** [comment] 2024-11-14 14:44
now seems to work but gives this on honeygain API Ping Error: api call: http request error: Post "https://api.honeygain.com/api/v1/ping": context deadline exceeded

**Comment by neve360** [comment] 2024-11-14 14:49
in the log  there is also this [2024-11-14T14:42:18Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:18Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:18Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:18Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:18Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:18Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:18Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:18Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:19Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:20Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:22Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:22Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:22Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:22Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:22Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:22Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:22Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:22Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy
[2024-11-14T14:42:23Z ERROR tun2proxy] Failed to create UDP connection: Protocol not supported by HTTP proxy

**Comment by neve360** [comment] 2024-11-14 14:51
meanwhile the other tunproxy its like this: time="2024-11-13T19:16:59Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2024-11-13T19:16:59Z" level=info msg="[STACK] tun://tun0 <-> http://ip:port"
time="2024-11-14T06:17:55Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2024-11-14T06:17:55Z" level=info msg="[STACK] tun://tun0 <-> http://ip:port"
time="2024-11-14T14:33:33Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2024-11-14T14:33:33Z" level=info msg="[STACK] tun://tun0 <-> http://ip::port"

**Comment by engageub** [comment] 2024-11-14 15:53
> now seems to work but gives this on honeygain API Ping Error: api call: http request error: Post "https://api.honeygain.com/api/v1/ping": context deadline exceeded

Your DNS connections are failing as HTTP does not support UDP. Its working fine with socks5 proxy.
Could you please use `USE_DNS_OVER_HTTPS` in `properties.conf` and try.
In the earlier versions, we were overriding the resolv.conf file.  Will have to switch to earlier versions which was working with http proxy if DNS over https does not work. 

Thank you

**Comment by engageub** [comment] 2024-11-14 15:57
> meanwhile the other tunproxy its like this: time="2024-11-13T19:16:59Z" level=info msg="[DIALER] set fwmark: 0x22b" time="2024-11-13T19:16:59Z" level=info msg="[STACK] tun://tun0 <-> http://ip:port" time="2024-11-14T06:17:55Z" level=info msg="[DIALER] set fwmark: 0x22b" time="2024-11-14T06:17:55Z" level=info msg="[STACK] tun://tun0 <-> http://ip:port" time="2024-11-14T14:33:33Z" level=info msg="[DIALER] set fwmark: 0x22b" time="2024-11-14T14:33:33Z" level=info msg="[STACK] tun://tun0 <-> http://ip::port"

There are no connections in tun2socks logs. This issue has to be addressed by tun2socks author or you will have to change VPS.

**Comment by engageub** [comment] 2024-11-14 16:16
> > now seems to work but gives this on honeygain API Ping Error: api call: http request error: Post "https://api.honeygain.com/api/v1/ping": context deadline exceeded
> 
> Your DNS connections seems to be failing as HTTP does not support UDP. Its working fine with socks5 proxy. Could you please set `USE_DNS_OVER_HTTPS` to `true` in `properties.conf` and try. In the earlier versions, we were overriding the resolv.conf file. Will have to switch to earlier versions which was working with http proxy if DNS over https does not work.
> 
> Thank you

I just tried `USE_DNS_OVER_HTTPS`  in tunproxy branch and its working fine.

**Comment by neve360** [comment] 2024-11-14 17:56
now i try it btw thank you for your help

**Comment by neve360** [comment] 2024-11-14 18:01
with that enable is this on honeygain Honeygain service is starting
API Ping Error: api call: http request error: Post "https://api.honeygain.com/api/v1/ping": context deadline exceeded
Honeygain service is connected and running

**Comment by neve360** [comment] 2024-11-14 18:02
iproyal seems to work

**Comment by neve360** [comment] 2024-11-14 18:04
do you have discord by any chance?

**Comment by engageub** [comment] 2024-11-14 22:24
Hello,
Thank you for the confirmation.
You may continue to use it that way on Google Cloud VPS.
I do have discord, but I seldom access it.
If you have queries, you may reach out here by creating a discussion. 
Closing the issue as this is not related to the script rather the dependent docker image. 

Thank you

**Closed by engageub** 2024-11-14 22:24 UTC

**Comment by neve360** [comment] 2024-11-15 05:02
do you have a fix for that honeygain bug?

**Comment by neve360** [comment] 2024-11-15 06:10
for those who will search this i found a very simple fix to that problem: a reboot, with that now im not having the api error and i got it working with tunproxy on google vps (disabling firewall)

**Comment by engageub** [comment] 2024-11-15 06:19
Hello,
Thank you for the update regarding this. Is disabling firewall mandatory on google VPS to work. This will raise security concerns.
Does tun2socks also work now after rebooting?

Thank you

**Comment by neve360** [comment] 2024-11-15 15:41
and i saw now on tunproxy its saying this [2024-11-15T15:20:24Z WARN  tproxy_config::linux] failed to bind mount custom resolv.conf onto /etc/resolv.conf, resorting to direct write

**Comment by engageub** [comment] 2024-11-15 15:47
> and i saw now on tunproxy its saying this [2024-11-15T15:20:24Z WARN tproxy_config::linux] failed to bind mount custom resolv.conf onto /etc/resolv.conf, resorting to direct write

Yes, this is the common error line at the beginning due to restrictions set in the tun2proxy container not to override that file.
Do you see connection logs.
What about tun2socks. Is it working after the reboot. 

Thank you

**Comment by neve360** [comment] 2024-11-15 15:50
no the tun2socks seems not not work and with tunproxy seems working but its sharing very low quantity of network seems like its off

**Comment by neve360** [comment] 2024-11-15 15:51
if i have iproyal and honeygain the script wouldn't be better like this? version: '3.8'
services:
  honeygain1:
    image: honeygain
    environment:
      - http_proxy=http://proxy1.example.com:3128
      - https_proxy=http://proxy1.example.com:3128
    container_name: honeygain1

  honeygain2:
    image: honeygain
    environment:
      - http_proxy=http://proxy2.example.com:3128
      - https_proxy=http://proxy2.example.com:3128
    container_name: honeygain2

  honeygain3:
    image: honeygain
    environment:
      - http_proxy=http://proxy3.example.com:3128
      - https_proxy=http://proxy3.example.com:3128
    container_name: honeygain3

**Comment by engageub** [comment] 2024-11-15 16:22
Hello,
If it was so easy to pass through environment variables, it would have already been implemented by many users.



Thank you

**Comment by neve360** [comment] 2024-11-15 16:52
im kinda new to docker i was searching some tutorials and the two i found was using kinda that solution

**Comment by engageub** [comment] 2024-11-15 17:02
These solutions were already tried, but neither Proxychains nor Redsocks worked at the time of implementation. It's possible that the documentation has since been updated, especially if you're studying Docker or using AI tools for assistance. When I initially implemented this, it was a new approach for me as well. Most of the public Honeygain scripts I encountered lacked a viable proxy solution. As a result, I had to develop and share a working solution.

**Comment by neve360** [comment] 2024-11-15 17:06
but i saw with us residential in a day they do less than 10mb

**Comment by engageub** [comment] 2024-11-15 17:24
The traffic depends on location and demand in the region.

**Comment by neve360** [comment] 2024-11-15 17:38
seems strange that low

**Comment by engageub** [comment] 2024-11-15 18:14
You can use that on other VPS or your Home PC to confirm if there is no issue with Google cloud VPS.
To maximize earnings, you can use other apps on same proxy. 
Make sure your connection speed and bandwidth are good.

**Comment by neve360** [comment] 2024-11-15 18:20
confirmed its still vps problem i run it from mac for like an hour and it did a lot better than the google vps im trying to find some settings but firewall disabled and ecc so i dont know what is it

**Comment by engageub** [comment] 2024-11-15 18:25
I don't use google VPS, so I cannot suggest you anything about it as I don't know how its designed internally or what customizations have been made in the linux OS.

**Comment by neve360** [comment] 2024-11-15 20:15
i got now aws vps

**Comment by neve360** [comment] 2024-11-15 20:18
perfect aws works

**Comment by neve360** [comment] 2024-11-15 20:19
if you guys find a solution to google let me now for now i just use aws (its better)

**Comment by engageub** [comment] 2024-11-17 11:51
Glad to know its working on other VPS providers.
You will have to raise a support ticket to google mentioning this script.
Just let them know that you don't have problem with other VPS providers and they will investigate and resolve the issue.

Thank you
