### ISSUE TITLE
exec ./honeygain: exec format error

### ISSUE THREAD

**Issue by Raffy142** [engageub/InternetIncome#155] opened 2024-09-24 12:21 UTC
### Discussed in https://github.com/engageub/InternetIncome/discussions/154

<div type='discussions-op-text'>

<sup>Originally posted by **Raffy142** September 24, 2024</sup>
Hi, today i have this problem
i use ubuntu 22.04 and when i restart this problem appears in the logs
![image](https://github.com/user-attachments/assets/88d04764-92cf-400d-9b60-34bca9c983c8)
![Screenshot_2](https://github.com/user-attachments/assets/37ec2334-0453-4a9f-bf26-1adde6bde953)
</div>

**Comment by Raffy142** [comment] 2024-09-24 12:22
> ### Discussed in #154
> Originally posted by **Raffy142** September 24, 2024 Hi, today i have this problem i use ubuntu 22.04 and when i restart this problem appears in the logs ![image](https://private-user-images.githubusercontent.com/22778382/370277473-88d04764-92cf-400d-9b60-34bca9c983c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODA4MTAsIm5iZiI6MTcyNzE4MDUxMCwicGF0aCI6Ii8yMjc3ODM4Mi8zNzAyNzc0NzMtODhkMDQ3NjQtOTJjZi00MDBkLTliNjAtMzRiY2E5Yzk4M2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEyMjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyOTRkZDJjYjdjZDNhNzQxYzY3OGQ5MDRjNGUyOTVhNzczMjVhNzFkMjc0NGI4NWRkZTdlNzkwNDVkMmM0NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ztaoab5KIgBG1yb0Q0-YTAV9KPxDZTnB-vmLJUGtz_0) ![Screenshot_2](https://private-user-images.githubusercontent.com/22778382/370277733-37ec2334-0453-4a9f-bf26-1adde6bde953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODA4MTAsIm5iZiI6MTcyNzE4MDUxMCwicGF0aCI6Ii8yMjc3ODM4Mi8zNzAyNzc3MzMtMzdlYzIzMzQtMDQ1My00YTlmLWJmMjYtMWFkZGU2YmRlOTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEyMjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNzlmZDI3NWNmMTVmZDEwNWIyMjgzMTAzNTcyNjA0ZjEzN2MyMGVkNWFkNzczMjMwZTI3MjI2NmIyYmFlMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e1Gbdcbc_i0H8fUsZv5kBHBIERCWuWVu5l8CL7T0Je0)

docker --version
Docker version 27.3.1, build ce12230

**Comment by engageub** [comment] 2024-09-24 13:32
Hello,
It looks like you are using arm64 architecture.
Older version of honeygain is being used with proxies as it has been confirmed to be working fine.
It only supports amd64 architecture by default. 
You may change the version to the latest in the code by replacing `honeygain/honeygain:0.6.6` with `honeygain/honeygain`  in `internetIncome.sh` file.


Thank you

**Comment by engageub** [comment] 2024-09-25 03:37
Closing this with respect to previous comment.

**Closed by engageub** 2024-09-25 03:37 UTC
