### ISSUE TITLE
Chrome eBesucher extension proposal

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#108] opened 2024-04-04 22:40 UTC
Hi :)

I played around with Google Chrome and eBesucher and managed to get it working with points when using this extension: https://chromewebstore.google.com/detail/all-fingerprint-defender/meojnmfhjkahlfcecpdcdgjclcilmaij would you consider adding this to the chrome profile?

**Comment by engageub** [comment] 2024-04-04 23:40
Random display is not available for the chrome docker version present in
script.
There is another docker image available similar to
 firefox but it only works for amd64. So it has not been added.
The extension can be considered. Already aware
of such extensions but if it keeps changing randomly in a session it might
be problem.

Thank you

**Comment by copystring** [comment] 2024-04-05 07:43
Yes, you're right. It worked for a short while, but overnight it stopped working.

**Comment by engageub** [comment] 2024-04-05 12:25
The minimum recommended size for display is1280 x 1024

https://www.ebesucher.de/faq/wie-kann-ich-mehr-verdienen

If the extension randomly generates that preferred display size it may give
earnings.

**Comment by copystring** [comment] 2024-04-05 21:50
I have installed Firefox and Chrome directly on my Server without VM or docker. It still does not get any points. Resolution is 1600x900. I don't know where to go from here.
eBesucher with your script in Firefox and direct connection on test branch works, but it seems it restarts too often. Every hours seems too much so it runs in the captcha which is never solved in Firefox.

**Comment by engageub** [comment] 2024-04-05 22:27
Hello,
Please comment line 386 in test branch after downloading the code. It will
not restart for firefox.
You can monitor the memory and restart manually when required. If there are
free solvers in firefox do
let me know.
Restart was intended to maintain consistent memory utilization of browser.

https://github.com/engageub/InternetIncome/blob/test/internetIncome.sh#L386

Thank you

**Comment by engageub** [comment] 2024-04-07 04:23
Closing this as the answer has been given in the previous comments. 

Thank you

**Closed by engageub** 2024-04-07 04:23 UTC
