### ISSUE TITLE
Honeygain/ Error processing authorisation

### ISSUE THREAD

**Issue by drdre-lab** [engageub/InternetIncome#165] opened 2024-10-28 17:18 UTC
An error has recently appeared Error processing authorisation with Honeygain. With new accounts. The authorization data is correct. The IP is not blocked. The login is successful on other devices. And through InternetIncome is such an error. I suspect that Honeygain have banned authorization via version 0.66.

**Comment by engageub** [comment] 2024-10-28 18:00
Hello,
Can you confirm this by removing 0.6.6 from the code.
Please replace `honeygain/honeygain:0.6.6` with `honeygain/honeygain` in the `internetIncome.sh` file.
0.6.6 was introduced on amd64 as users had issues with newer version earlier.
It may also be possible that your password has special characters or your proxy is blocking something. 

Thank you

**Comment by drdre-lab** [comment] 2024-10-29 04:36
Conducted tests. The version of Honeygain is not to blame. The problem is in the proxy functionality InternetIncome:test. If I use a direct connection, then authorization is successful with the same data. If I connect via proxy, then "Error processing authorisation". The proxy and ip is definitely not banned - they work perfect in Honeygain Windows. There is no authorization with proxy in InternetIncome.

**Comment by drdre-lab** [comment] 2024-10-29 15:14
> Did you change the version in the code before testing?

Yes, I changed the code to use the latest version of Honeygain.

**Comment by engageub** [comment] 2024-10-29 15:29
Thank you for the confirmation. 
In that case there is no issue with the version.
Could you please confirm if other apps are working fine on the same proxy.
Please also check tun2socks logs if there is any issue with your proxy.
Your proxy provider may also be blocking requests. 

Thank you

**Comment by drdre-lab** [comment] 2024-10-29 17:20
Thank you very much for your advice. The problem was in dns over socks.

**Comment by engageub** [comment] 2024-10-29 17:51
Thank you for the update.
Please use default settings to avoid any issues as they have been confirmed to be working fine.
Use Socks5 DNS if your Proxy supports it else use the default configuration. 
Closing the issue as the root cause has been identified.

**Closed by engageub** 2024-10-29 17:51 UTC
