### ISSUE TITLE
Purchased proxy bandwidth is not displayed on the web list

### ISSUE THREAD

**Issue by MuoiTom** [engageub/InternetIncome#140] opened 2024-07-12 04:05 UTC
I bought a proxy on a website list but using the tool does not jump the bandwidth. Please guide me how to install it on a website that sells proxies

**Comment by engageub** [comment] 2024-07-12 04:20
Hello,
You will have to check with proxy provider for bandwidth related issues.
Could you please provide more details on what app, you are trying to access.
All the relevant details and FAQ are mentioned in the following link.
https://github.com/engageub/InternetIncome 

Thank you

**Comment by MuoiTom** [comment] 2024-07-12 04:27
You will have to check with proxy provider for bandwidth related issues. I don't know how to install proxy to run internetincome tool, please guide me to install.
I run traffmontizer earnapp earnfm and proxyrack
Thank you  please guide me to install

**Comment by MuoiTom** [comment] 2024-07-12 04:29
web proxy https://proxyelite.info I run the internetincome tool but the bandwidth share does not jump

**Comment by MuoiTom** [comment] 2024-07-12 04:30
![image](https://github.com/user-attachments/assets/b782abd5-fc34-481e-8fe6-0118b2a60414)
I need to make corrections here, right? Please guide me

**Comment by engageub** [comment] 2024-07-12 04:34
Hello,
Is the binding IP correct?  Do you see your apps online in their respective dashboard.

Thank you

**Comment by MuoiTom** [comment] 2024-07-12 04:36
ip binding is correct. see the ip there. Is this a website that shares traffic or a website that sells proxies?

**Comment by engageub** [comment] 2024-07-12 04:39
Is that your VPS IP address?
If so, can you login to your VPS and run the following command.
Replace `<YOUR_PROXY_HERE>` with proxy in the format `protocol://username:password@IP:PORT`.

```
curl -x <YOUR_PROXY_HERE> https://google.com
```

Thank you

**Comment by MuoiTom** [comment] 2024-07-12 04:40
web answer like this so this proxy can't run traffic right? For all our proxies, binding to real ip is mandatory, proxy will work from this device only. You can reconnect an unlimited number of times.
The exception is spinning proxies (proxies change with each new request), they do not need binding, proxies work with login and password authorization

**Comment by MuoiTom** [comment] 2024-07-12 04:42
> Is that your VPS IP address? If so, can you login to your VPS and run the following command. Replace `<YOUR_PROXY_HERE>` with proxy in the format `protocol://username:password@IP:PORT`.
> 
> ```
> curl -x <YOUR_PROXY_HERE> https://ifconfig.me
> ```
> 
> Thank you

Isn't that the ipve res proxy I bought at https://proxyelite.info/

**Comment by engageub** [comment] 2024-07-12 04:45
If you are using rotating proxies, your accounts may get banned. You will have to use static IP address.

They usually provide only Datacenter proxies. 

https://github.com/engageub/InternetIncome/wiki/Proxies-and-Hosting-Providers 

Thank you

**Comment by engageub** [comment] 2024-07-12 04:46
> > Is that your VPS IP address? If so, can you login to your VPS and run the following command. Replace `<YOUR_PROXY_HERE>` with proxy in the format `protocol://username:password@IP:PORT`.
> > ```
> > curl -x <YOUR_PROXY_HERE> https://ifconfig.me
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you
> 
> Isn't that the ipve res proxy I bought at https://proxyelite.info/

If the response is not your VPS IP, then it is your proxy you purchased.

**Comment by MuoiTom** [comment] 2024-07-12 05:02
> If you are using rotating proxies, your accounts may get banned. You will have to use static IP address.
> 
> They usually provide only Datacenter proxies.
> 
> https://github.com/engageub/InternetIncome/wiki/Proxies-and-Hosting-Providers
> 
> Thank you

I bought a static proxy from the above website list but I can't use it. Can you show me which website can run traffic? I bought web number 9

**Comment by MuoiTom** [comment] 2024-07-12 05:13
yes thank you very much maybe I chose the wrong website that sells proxies. Please close this issue. thanks a lot

**Comment by engageub** [comment] 2024-07-12 05:25
> > If you are using rotating proxies, your accounts may get banned. You will have to use static IP address.
> > They usually provide only Datacenter proxies.
> > https://github.com/engageub/InternetIncome/wiki/Proxies-and-Hosting-Providers
> > Thank you
> 
> I bought a static proxy from the above website list but I can't use it. Can you show me which website can run traffic? I bought web number 9

You may purchase from the list which support residential proxies.

https://github.com/engageub/InternetIncome/wiki/Proxies-and-Hosting-Providers

If you are using apps which support only data center IP address, you can still use the elite proxies.
If the curl command mentioned above works, you can continue using it with the script.

Thank you

**Comment by engageub** [comment] 2024-07-12 05:27
Is this the first time, you are accessing the script or have you used it with other proxies also?

Thank you

**Comment by engageub** [comment] 2024-07-12 06:50
Closing this as there the issue is not related to the Script.

Thank you

**Closed by engageub** 2024-07-12 06:50 UTC
