### ISSUE TITLE
Apps Performance

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#7] opened 2023-05-23 11:09 UTC
Apps Performance:
EarnAPP: terrible 200mb per day
Honeygain: Good ~30GB per day
PawnsAPP: I am not using it
ProxyRack: terrible and barely working 0.1GB per day
PacketStream: Good 8GB per day
Traffimonitizer: working with low traffic 3GB per day
Repocket: Working but the network is saturated few cents per day
Ebuscher: I am not using it
ProxyLite: I am not using it
Mysterium: Testing one node

App Performance on my manual setup:
EarnAPP: Fair 6.5GB per day
Honeygain: Good ~30GB per day
PawnsAPP: I am not using it
ProxyRack: Good 9GB per day
PacketStream: Good 8GB per day
Traffimonitizer: Good 8GB per day
Repocket: Working but the network is saturated few cents per day
Ebuscher: I am not using it
ProxyLite: I am not using it
Mysterium: I am not using it

Conclusion:
There are issues with EarnAPP, ProxyRack and Traffmonitizer for some reason, i have been using the same proxies on the same machine, RAM is ~50% used CPU is ~55% used, Internet Speed 1GBPS shared, number of proxies 100

**Comment by engageub** [comment] 2023-05-23 19:38
Hi,
Thank you for providing the stats. Could you please let me know if you have used the proxies on same location.
Also earnapp checks the CPU and memory. You may have a look at the logs if it shows that CPU is not idle.
It was working good as other users confirmed it and it had good traffic. 
Also, I am assuming that your PC was not rebooted and the instances were running since the start of the script. 
If you rebooted the PC while it was already running DNS may not work if your proxy does not support UDP. 
I would like to know how you tested manually with 100 proxies. Do you have 100 instances?

Thank you

**Comment by SkullFace141** [comment] 2023-05-23 20:19
same proxies, same machine.
the manual setup has 100 LXC containers, each container has 1 proxy and 1 instance of each app

**Comment by engageub** [comment] 2023-05-23 23:24
Thank you for the data. You may have to check with the respective container app owners who are maintaining this. The script has been tested for proxy use and deployed. 
It cannot be confirmed on what is going on unless the issue has been identified. There might be many reasons why this is occurring with earnapp application. The traffic is very low when compared to the manual setup.  Users claim  they get about 2GB traffic per day from 10 IP for earnapp in US region.  
Looking at the honeygain data, it is consistent across both docker and LXC. The script has no impact and it only proxies the containers using the available applications.  If it is not working as expected you may raise an issue.
Also how is the CPU and memory utilization when compared to LXC and docker containers. Do 100 instances of LXC containers use the same CPU and memory as the docker containers for the same number of apps used.

Thank you

**Comment by SkullFace141** [comment] 2023-05-24 07:08
LXC use more resources

**Comment by engageub** [comment] 2023-05-24 19:24
Thank you for the confirmation. So docker is performing better when compared to LXC but earnings are not as good as LXC containers according to your system analysis.
If you have good CPU and memory, you can install salad and see your earnings. Some of the countries it pays about $1 per day. 

Thank you

**Comment by engageub** [comment] 2023-05-25 15:44
Can you please provide an update if there are any additional tasks remaining in this matter?

Thank you

**Comment by engageub** [comment] 2023-05-26 02:01
Closing this since this is not an issue and no further updates have made on this.

**Closed by engageub** 2023-05-26 02:01 UTC

**Comment by contidz** [comment] 2023-07-05 20:08
I can refer to honeygain how many proxies do you use to get 30gb/day
