### ISSUE TITLE
eBesucher not working after a while

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#17] opened 2023-06-05 19:20 UTC
Hi,

I have observed, that the container is not restarted.
What kind of logs can I provide for further debugging of the problem?

**Comment by engageub** [comment] 2023-06-05 19:44
Hello,
Ebesucher restarts every one hour automatically. 
Please answer the following queries.
1. Are you using Proxy or direct connection?
2. Can you run the following command and provide the output here.
```
sudo docker container ls| grep firefox
```
```
sudo docker container ls| grep dind
```
3. The above commands display when they were initiated and when was the last time the containers are restarted.


Thank you

**Comment by copystring** [comment] 2023-06-05 20:54
> Hello, Ebesucher restarts every one hour automatically. Please answer the following queries.

It does not restart every hour in my case.
> 
> 1. Are you using Proxy or direct connection?

No proxy. Just direct connection.

> 2. Can you run the following commands and provide the output here.
> 
> ```
> sudo docker container ls| grep firefox
> ```
> 
```
sudo docker container ls| grep firefox
c23dc794a926   jlesage/firefox:latest                 "/init"                  7 days ago    Up 35 hours             5900/tcp, 0.0.0.0:3000->5800/tcp, :::3000->5800/tcp                                              funny_williams
```
> ```
> sudo docker container ls| grep dind
> ```
> 

```
sudo docker container ls| grep dind
3dac9ec4c4e5   docker:18.06.2-dind                    "dockerd-entrypoint.…"   2 weeks ago   Up 38 hours             2375/tcp                                                                                         laughing_shannon
```

**Comment by engageub** [comment] 2023-06-05 21:22
Thank you for the response. It looks like you restarted your PC.  The containers should have nearly same created times.
The dind container was started two weeks back but the uptime is 38 hours which is supposed to be 2 weeks ago if you did not restart your PC or no updates and the firefox container was started 7 days ago.
The firefox container is not being restarted. The uptime should not be more than 1 hour but it has been running for over 35 hours.
Do you have watchtower installed to auto update containers? 
Is your CPU, RAM and diskspace normal?

Thank you

**Comment by copystring** [comment] 2023-06-05 21:32
Yes. I restarted yesterday hoping it would solve the problem. RAM, disk and CPU usage is normal. It just stopped working at about 3pm. Checked the browser of the container. It could not find the domain ebesucher.de so I guess there was no internet. Anyway, the container does not restart.

**Comment by engageub** [comment] 2023-06-05 21:54
Thank you. Firefox was updated 9 days back. So the container id might have been changed.
Could you please open containers.txt and see if the container ids are present in the file. Please see the beginning of each container id below in the containers.txt file. If either of them is missing it will not work.
You will however have to delete and start the script since it is not working as expected but to know the reason you will need to look into the following before doing so.

c23dc794a926   
3dac9ec4c4e5   

Thank you

**Comment by engageub** [comment] 2023-06-05 22:10
It looks like this is caused by watchtower update. Please stop watchtower and delete and start the script when necessary. 
The script always checks for updates before starting a container. So if you want to update something just use --delete and then --start and it will automatically update the containers.

You will need to manually delete the containers if new container ids are generated by watch tower updates. So, it is better to stop using it. 
FAQ section will be updated, if this is the reason that caused the issue. 

Thank you

**Comment by engageub** [comment] 2023-06-05 23:46
Please note that you have to manually delete the containers using the following command if the script does not delete.
It can be confirmed that the issue occurred due to watchtower updates.  There may be other containers running on your host which the script may not have deleted. 

To delete firefox related containers mentioned above, please use the following command. 
```
  sudo docker rm -f c23dc794a926   3dac9ec4c4e5
```

To delete all docker containers on your host use the following command. The command deletes all stale containers and running containers on your host.

```
sudo docker container ls -a | awk '{print $1}' | xargs sudo docker rm -f
```

Do not use watch tower until the next update has been pushed to main branch.
You may start using the script as usual but without watchtower container running. 
The related changes to use container names instead of container ids have been pushed to test branch.


Thank you

**Comment by engageub** [comment] 2023-06-05 23:51
Closing this since the script is working as expected. As mentioned do not use watchtower updates till the next version is released.

Thank you

**Closed by engageub** 2023-06-05 23:51 UTC

**Comment by engageub** [comment] 2023-06-06 06:51
Hi,
The code has been pushed to main branch, please download the latest version in new folder and use the script.
You may use watchtower now.

Thank you

**Comment by copystring** [comment] 2023-06-06 19:15
Okay. I will test this now. I did not make any changes to my setup yet. Do I still need to delete anything or just rerun the script?

**Comment by engageub** [comment] 2023-06-06 21:08
Yes, you need to delete all containers as mentioned above and start. 
If you are not using watch tower, there will not be any problems with the script interruption in the old script that you have.

If you wish to use watch tower, please download the latest script from github again and start the containers. 


Thank you

**Comment by copystring** [comment] 2023-07-02 17:38
Hi @engageub, the issue is back again. It's been running for a while, but on the 26.06.2023 it started to fail just like before. Now the container is running for 6 days straight.

```
sudo docker container ls| grep firefox
5f1ecd25f167   jlesage/firefox:latest                 "/init"                  6 days ago    Up 6 days             5900/tcp, 0.0.0.0:3000->5800/tcp, :::3000->5800/tcp                                              crazy_lehmann
```
```
sudo docker container ls| grep dind
014aec55d6ed   docker:18.06.2-dind                    "dockerd-entrypoint.…"   3 weeks ago   Up 7 days             2375/tcp                                                                                         flamboyant_lamport
```

**Comment by engageub** [comment] 2023-07-02 17:43
Hi,
It looks like you are not using the latest version as mentioned. The container names are different.
Thank you

**Comment by copystring** [comment] 2023-07-02 20:45
OK. I recreated everything with the latest version of InternetIncome.

**Comment by engageub** [comment] 2023-07-02 20:51
Do you see the difference in container names?

**Comment by copystring** [comment] 2023-07-02 20:53
Yes. They are all different now. Each of them starting with the name of the ebesucher, pawn, etc
