### ISSUE TITLE
eBesucher not working correctly after a while

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#5] opened 2023-05-21 20:25 UTC
I've set up the eBesucher container. It runs for a while. Eventually there's a new tab besides the actual eBesucher tab, thus the actual eBesucher tab is not in focus and no points are generated anymore. When this happens I have to click through the initial questions of Firefox just like when it's installed the first time.
Is the container of eBesucher restarted after a while causing this problem?

**Comment by engageub** [comment] 2023-05-21 20:32
Hi,
Ebesucher restarts after 1 hour in order to make sure memory does not increase gradually. 
The data is cleared every hour automatically and starts again with how it was started when initially. 
Please make sure you only use residential proxies, else it may ask for captcha. 

Thank you

**Comment by copystring** [comment] 2023-05-21 20:43
>The data is cleared every hour automatically and starts again with how it was started initially. 

It has nothing to do with any proxy. I don't have any. Feels like the state of Firefox is stored in a way, that the empty tab is saved with it and also needs the initial configuration every time. How do I fix that?

**Comment by copystring** [comment] 2023-05-21 20:46
![image](https://github.com/engageub/InternetIncome/assets/1298861/33bb632f-9240-4cc1-926c-370a69633da3)

**Comment by engageub** [comment] 2023-05-21 21:09
Thank you for the screenshot. The firefox container was updated two days ago. 
I just pulled the latest container now and I see the tab too. 
The config will be updated soon. Thank you. 

https://hub.docker.com/r/jlesage/firefox
Thank you

**Comment by engageub** [comment] 2023-05-21 21:44
Hi,
Could you please update the code now. I pushed the changes already. 
Let me know if its working fine now.

Thank you

**Comment by engageub** [comment] 2023-05-22 17:11
Closing this since the issue is resolved and there has been no update from the issue raiser.

Thank you

**Closed by engageub** 2023-05-22 17:11 UTC

**Comment by copystring** [comment] 2023-05-22 19:00
Thank you for solving the problem. I started the updated instance this morning before work, and it's been running all day just fine.
