### ISSUE TITLE
[Feature Request] How can i use the script on a machine that has multiple public IPs?

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#9] opened 2023-05-25 09:05 UTC
How can i use the script on a machine that has multiple public IPs?

ex: a machine with a subnet, has 1 real NIC and mutiple virtual NICs for the other IPs.

Thanks

**Comment by engageub** [comment] 2023-05-26 02:10
Hi, 
The changes will be made on this. But you are required to test it once the changes are pushed to test branch since there are no production servers available with multiple IPs assigned to it. Proxies are different from using multiple IPs.
Also please note that if you are using IPs, proxies will not be used. It can still be done with proxy over the IP, but I don't think its required since you are using an IP directly and if you are using proxies, use the proxies directly instead of going through multiple IPs. 
This is a scenario where you are using multiple connections from ISP provider and not using proxy IP address. 

Thank you

**Comment by engageub** [comment] 2023-05-26 18:17
Hi,
Could you please test using the following commands for peer2profit. The IP address will be shown in the dashboard. If your NIC is already configured and network works by default. Then use the following commands.
We are creating a docker network with the NIC and using that network in docker run command. 
In the following commands replace the following 

<parent_interface> --> Provide your network interface name 
<network_name> --> Use any name but use the same name across all commands
<your_email> --> Your peer2profit email address

```
sudo docker network create -d macvlan -o parent=<parent_interface> <network_name>
sudo docker  run -d  -e P2P_EMAIL=<your_email>  --name peer2profit  --network <network_name> peer2profit/peer2profit_linux:latest 
```

Visit your peer2profit dashboard and check if your IP address of NIC attached is visible. 

To delete the above created containers run the following

```
sudo docker rm  -f peer2profit  
sudo docker network rm  <network_name>
```

If the above works fine, then it can be automated by simply using interface names. 

Thank you

**Comment by engageub** [comment] 2023-05-30 00:23
Hi,
Could you please update if the above command has been confirmed working. However there is already a working solution provided in traffmonetizer documentation.
It uses both docker network and iptables instead of single command. 

https://hub.docker.com/r/traffmonetizer/cli

Thank you

**Comment by SkullFace141** [comment] 2023-06-04 13:15
please update the script to use text file for ip and interface config
example network.txt that has interface name and IP and any other needed info

**Comment by engageub** [comment] 2023-06-04 23:14
Yes, the implementation for this is not a problem. But a confirmation was required to know if the commands mentioned works for single IP on your host.

Thank you

**Comment by engageub** [comment] 2023-06-05 12:53
Gentle reminder. please confirm if you tested the three commands mentioned for peer2profit.

Thank you

**Comment by engageub** [comment] 2023-06-05 19:11
Do you have multiple IP's now or it was just a request for planning later. 

Thank you

**Comment by engageub** [comment] 2023-06-13 00:40
Could you please update on this. Did you test this yet?

Thank you

**Comment by engageub** [comment] 2023-06-25 18:27
@SkullFace141 ,
Gentle reminder. Any update on this.

Thank you

**Comment by SkullFace141** [comment] 2023-07-04 20:13
sorry I don't have this in my current setup

**Comment by engageub** [comment] 2023-11-06 21:55
Changes have been pushed to test branch based on the documentation for traffmonetizer. 
https://hub.docker.com/r/traffmonetizer/cli_v2

This has not been tested with real machine with multiple IPs. 
You may test it anytime to confirm on this. 
https://github.com/engageub/InternetIncome/tree/test
I am closing this one. 

Thank you

**Closed by engageub** 2023-11-06 21:55 UTC
Labels: enhancement
