### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by xander710** [engageub/InternetIncome#43] opened 2023-08-03 20:19 UTC
Getting these errors when trying to start the script. I have created vps servers with this software before but suddenly I am getting these errors. Everything is installed correctly.

Starting..

USE_PROXIES is enabled, using proxies..
Starting Proxy container..
v2.5.0: Pulling from xjasonlyu/tun2socks
Digest: sha256:3e8ea391021663ae2edf9fbee9cb2d08087444e646eab468ea2ccbb260f1f6c1
Status: Image is up to date for xjasonlyu/tun2socks:v2.5.0
[docker.io/xjasonlyu/tun2socks:v2.5.0](http://docker.io/xjasonlyu/tun2socks:v2.5.0)
dbc13fc1b272bf7fa8c16529eb16fa7e582392f2c5e533a5672c281e63a748b1
tun0d8b5e804141b2297b65df6ff6c9ce271
OCI runtime exec failed: exec failed: cannot exec in a stopped container: unknown
Mysterium Node is not enabled. Ignoring Mysterium..
Ebesucher username is not configured. Ignoring Ebesucher..
BitPing Node is not enabled. Ignoring BitPing..
Starting Repocket container..
Using default tag: latest
latest: Pulling from repocket/repocket
Digest: sha256:9e1ced07a10b2c6e7c0ad38ed241b403f1c203c1a03d5b655794b56ce13566b3
Status: Image is up to date for repocket/repocket:latest
[docker.io/repocket/repocket:latest](http://docker.io/repocket/repocket:latest)
docker: Error response from daemon: Container dbc13fc1b272bf7fa8c16529eb16fa7e582392f2c5e533a5672c281e63a748b1 is restarting, wait until the container is running.
Failed to start container for Repocket..
Starting Traffmonetizer container..
Using default tag: latest
latest: Pulling from traffmonetizer/cli
Digest: sha256:7114b73838077303e14ac834d2e5c7e2491be388c2578752593f1ffef1c8a8db
Status: Image is up to date for traffmonetizer/cli:latest
[docker.io/traffmonetizer/cli:latest](http://docker.io/traffmonetizer/cli:latest)
docker: Error response from daemon: Container dbc13fc1b272bf7fa8c16529eb16fa7e582392f2c5e533a5672c281e63a748b1 is restarting, wait until the container is running.
Failed to start container for Traffmonetizer..
ProxyRack Api is not configured. Ignoring ProxyRack..
IPRoyals Email or Password is not configured. Ignoring IPRoyals..
Honeygain Email or Password is not configured. Ignoring Honeygain..
Peer2Profit Email is not configured. Ignoring Peer2Profit..
Starting PacketStream container..
latest: Pulling from packetstream/psclient
Digest: sha256:6cf075d43009c220abb10c1a037786eb513c93f5146a9bba8bed486d0e4bd970
Status: Image is up to date for packetstream/psclient:latest
[docker.io/packetstream/psclient:latest](http://docker.io/packetstream/psclient:latest)
docker: Error response from daemon: Container dbc13fc1b272bf7fa8c16529eb16fa7e582392f2c5e533a5672c281e63a748b1 is restarting, wait until the container is running.
Failed to start container for PacketStream..
Proxylite is not configured. Ignoring Proxylite..
Earnapp is not enabled. Ignoring Earnapp..
Starting Proxy container..
1a9e0af24e4c23982ca3ebe9c653744fe61d9ca9ff67649694fff805191774bd
tun0d8b5e804141b2297b65df6ff6c9ce272
OCI runtime exec failed: exec failed: unable to start container process: error executing setns process: exit status 1: unknown
Starting Repocket container..
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/17050/ns/net: no such file or directory: unknown.
Failed to start container for Repocket..
Starting Traffmonetizer container..
docker: Error response from daemon: Container 1a9e0af24e4c23982ca3ebe9c653744fe61d9ca9ff67649694fff805191774bd is restarting, wait until the container is running.
Failed to start container for Traffmonetizer..
Starting PacketStream container..
docker: Error response from daemon: Container 1a9e0af24e4c23982ca3ebe9c653744fe61d9ca9ff67649694fff805191774bd is restarting, wait until the container is running.
Failed to start container for PacketStream..

**Comment by engageub** [comment] 2023-08-03 21:20
Looks like your proxies in proxies.txt are not in correct format.
Could you please let me know the format used for proxies in proxies.txt.
Also are you using http or socks5 proxies.

Thank you

**Comment by engageub** [comment] 2023-08-04 03:02
Closing this considering that the issue is with proxy format. Please make sure there are no special characters at the end of each line in proxies.txt file.
Feel free to reopen in case you still see any issues. 
Thank you

**Closed by engageub** 2023-08-04 03:02 UTC

**Comment by xander710** [comment] 2023-08-04 08:54
Hello, thanks for your answer.
It has indeed something to do with the proxies. when I turn proxies off, the program works. However, I have made sure now that the proxies are in the correct format (socks5://user:pass@ip:port and it still seems togive the same error. I have tried to do it on a fresh linux install but am getting the same issues.

**Comment by engageub** [comment] 2023-08-04 09:09
Hi,
Could you please let me know if you are using ubuntu or other linux versions. 
Are you copying and pasting the proxies from somewhere else. If so, can you type one proxy manually in proxies.txt file and see if its working fine.
Can you also enable logs from properties.conf file .
Then run the following command . For example if your tun2socks container was tun0d8b5e804141b2297b65df6ff6c9ce271 use the following command and replace it with the container name you see on the screen after running the script.
```
sudo docker container logs tun0d8b5e804141b2297b65df6ff6c9ce271

```
Thank you

**Comment by xander710** [comment] 2023-08-04 09:34
I tried typing one in manually but it gave me the same error, I also double checked if the proxy is working and that seems to be fine as well. I have requested the log for the tun2socks container and it reads this, I have hidden my username, password and ip.


tun36426b22b500b98b3a5eb4d11c81d9741: command not found
root@localhost:~/InternetIncome-main# sudo docker container logs tun36426b22b500b98b3a5eb4d11c81d9741
time="2023-08-04T09:28:34Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:28:34Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"
time="2023-08-04T09:28:35Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:28:35Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"
time="2023-08-04T09:28:35Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:28:35Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"
time="2023-08-04T09:28:36Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:28:36Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"
time="2023-08-04T09:28:37Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:28:37Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"
time="2023-08-04T09:28:39Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:28:39Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"
time="2023-08-04T09:28:42Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:28:42Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"
time="2023-08-04T09:28:49Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:28:49Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"
time="2023-08-04T09:29:02Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-08-04T09:29:02Z" level=fatal msg="[ENGINE] failed to start: parse \"socks5://x:pw@ip:5501\\r\                                          ": net/url: invalid control character in URL"

**Comment by engageub** [comment] 2023-08-04 09:39
There seems to be special characters at the end of the line.
Please run the following command to remove them.

```
sed -i 's/\r//g' proxies.txt
```
After this command run the script.

Thank you

**Comment by xander710** [comment] 2023-08-04 09:44
That seems to have fixed it! thank you very much.

**Comment by engageub** [comment] 2023-08-04 09:46
It looks like you are using GUI editor instead of vi editor which is introducing special characters at the end of the file.
However this will be added in the code soon to handle this use case. 

Thank you

**Comment by engageub** [comment] 2023-08-04 09:49
You may disable the logs now and run it by adding all the proxies. Make sure you run the command to remove special characters before running the script.
Thank you

**Comment by engageub** [comment] 2023-08-04 10:00
If you are using GUI editor for properties.conf, you may also have to run the following, just in case your passwords are not working. 
Try to use vi editor as mentioned in the description to avoid introducing special characters. 

```
sed -i 's/\r//g' properties.conf
```
